package Vista;
import BaseDeDatos.JDBC;
import java.awt.GridLayout;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import modelo.Contacto;
import modelo.Perfil;
import modelo.Publicacion;
import modelo.Usuario;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class VentanaVisitante extends javax.swing.JFrame {

    
    private Usuario usser;
    private Usuario visit;
    private Perfil perfil;
    
    /**
     * 
     * @param u es el usuario al que estamos visitando
     * @param v es el usuario que va a visitar(es el usuario logueado)
     */
    public VentanaVisitante(Usuario u,Usuario v) {
        this.usser = u;
        this.perfil = usser.getPerfil();
        this.visit=v;
        initComponents();
        llenarCampos();
        setLocationRelativeTo(null);
        URL imgURL = getClass().getResource("/resource/iconoFacebook.png");
        this.setIconImage((new ImageIcon(imgURL)).getImage());
    }

    public VentanaVisitante(){
        initComponents();
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatar = new ImagePanel();
        portada = new ImagePanel();
        jPanel3 = new javax.swing.JPanel();
        icono = new ImagePanel();
        jPanel1 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        nik = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        pais = new javax.swing.JLabel();
        ciudad = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        contenedorAmigos = new javax.swing.JScrollPane();
        amigos = new javax.swing.JPanel();
        contenedorQuizas = new javax.swing.JScrollPane();
        quizas = new javax.swing.JPanel();
        estado = new javax.swing.JLabel();
        colegio = new javax.swing.JLabel();
        universidad = new javax.swing.JLabel();
        trabajo = new javax.swing.JLabel();
        religion = new javax.swing.JLabel();
        fono = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        muro = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        publicar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ((ImagePanel)avatar).setBackgroundImage(perfil.getAvatar());
        avatar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        avatar.setPreferredSize(new java.awt.Dimension(230, 225));

        javax.swing.GroupLayout avatarLayout = new javax.swing.GroupLayout(avatar);
        avatar.setLayout(avatarLayout);
        avatarLayout.setHorizontalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        avatarLayout.setVerticalGroup(
            avatarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ((ImagePanel)portada).setBackgroundImage(perfil.getPortada());
        portada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        portada.setPreferredSize(new java.awt.Dimension(761, 236));

        javax.swing.GroupLayout portadaLayout = new javax.swing.GroupLayout(portada);
        portada.setLayout(portadaLayout);
        portadaLayout.setHorizontalGroup(
            portadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        portadaLayout.setVerticalGroup(
            portadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(230, 236));

        ((ImagePanel)icono).setBackgroundImage(perfil.getIcono());

        javax.swing.GroupLayout iconoLayout = new javax.swing.GroupLayout(icono);
        icono.setLayout(iconoLayout);
        iconoLayout.setHorizontalGroup(
            iconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        iconoLayout.setVerticalGroup(
            iconoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 255))); // NOI18N
        jPanel1.setOpaque(false);

        nombre.setForeground(new java.awt.Color(153, 153, 153));
        nombre.setText("Nombre");

        nik.setForeground(new java.awt.Color(153, 153, 153));
        nik.setText("Nik");

        email.setForeground(new java.awt.Color(153, 153, 153));
        email.setText("E-mail");

        pais.setForeground(new java.awt.Color(153, 153, 153));
        pais.setText("País");

        ciudad.setForeground(new java.awt.Color(153, 153, 153));
        ciudad.setText("Ciudad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ciudad)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(icono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout amigosLayout = new javax.swing.GroupLayout(amigos);
        amigos.setLayout(amigosLayout);
        amigosLayout.setHorizontalGroup(
            amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );
        amigosLayout.setVerticalGroup(
            amigosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        contenedorAmigos.setViewportView(amigos);

        jTabbedPane2.addTab("Amigos", contenedorAmigos);

        estado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        estado.setForeground(new java.awt.Color(51, 102, 255));
        estado.setText("Estado");
        estado.setText(perfil.getEstado());

        colegio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        colegio.setForeground(new java.awt.Color(51, 102, 255));
        colegio.setText("Colegio");
        colegio.setText(perfil.getColegio());

        universidad.setText(perfil.getUniversidad());
        universidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        universidad.setForeground(new java.awt.Color(51, 102, 255));
        universidad.setText("Universidad");
        universidad.setText(perfil.getUniversidad());

        trabajo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        trabajo.setForeground(new java.awt.Color(51, 102, 255));
        trabajo.setText("Trabajo");
        trabajo.setText(perfil.getTrabajo());

        religion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        religion.setForeground(new java.awt.Color(51, 102, 255));
        religion.setText("Religion");
        religion.setText(perfil.getReligion());

        fono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fono.setForeground(new java.awt.Color(51, 102, 255));
        fono.setText("Telefono");
        fono.setText(String.valueOf(usser.getFono()));

        javax.swing.GroupLayout quizasLayout = new javax.swing.GroupLayout(quizas);
        quizas.setLayout(quizasLayout);
        quizasLayout.setHorizontalGroup(
            quizasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(quizasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(colegio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(universidad, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(trabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(religion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        quizasLayout.setVerticalGroup(
            quizasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colegio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(universidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trabajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(religion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fono)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        contenedorQuizas.setViewportView(quizas);

        jTabbedPane2.addTab("Informacion", contenedorQuizas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout muroLayout = new javax.swing.GroupLayout(muro);
        muro.setLayout(muroLayout);
        muroLayout.setHorizontalGroup(
            muroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );
        muroLayout.setVerticalGroup(
            muroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(muro);

        publicar.setText("Publicar");
        publicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicarActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(texto);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(18, 18, 18)
                .addComponent(publicar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publicar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(portada, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(portada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avatar, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void publicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicarActionPerformed
        if(texto.getText().length()>0){
            //------------------------------------------>>>>>>>(String autor, String fecha, String detalle, String codU, String codPer)
            Publicacion p = new Publicacion(visit.getNom()+" "+ visit.getApe(),new Date().toString(),texto.getText(),visit.getCodU(), usser.getPerfil().getCodigoPe());
            JDBC.getJDBC().agregarPublicacion(p);
            perfil.getMuro().agregarPublicacion(p);
            refresh();
        }
    }//GEN-LAST:event_publicarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaVisitante v = new VentanaVisitante();
                v.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel amigos;
    private javax.swing.JPanel avatar;
    private javax.swing.JLabel ciudad;
    private javax.swing.JLabel colegio;
    private javax.swing.JScrollPane contenedorAmigos;
    private javax.swing.JScrollPane contenedorQuizas;
    private javax.swing.JLabel email;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fono;
    private javax.swing.JPanel icono;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel muro;
    private javax.swing.JLabel nik;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel pais;
    private javax.swing.JPanel portada;
    private javax.swing.JButton publicar;
    private javax.swing.JPanel quizas;
    private javax.swing.JLabel religion;
    private javax.swing.JTextPane texto;
    private javax.swing.JLabel trabajo;
    private javax.swing.JLabel universidad;
    // End of variables declaration//GEN-END:variables
    //mis variables
    private ArrayList<Contacto> contactos;
    private ArrayList<Publicacion> pubs;
    
    
    private void llenarCampos() {
        nombre.setText(usser.getNom()+" "+usser.getApe());
        nik.setText(usser.getNik());
        email.setText(usser.getEmail());
        pais.setText(usser.getPais());
        ciudad.setText(usser.getCiudad());
        
        contactos = usser.getPerfil().getContactos();
        //cargamos contactos
        amigos.setLayout(new GridLayout(contactos.size()+5,1));  
        for (Contacto contacto : contactos) {
            contacto.setCodPerfil(null);
             amigos.add(new ContactoVista(contacto,visit));   
        }
        
        pubs = usser.getPerfil().getMuro().getPubs();
        
        
        //cargamos publicaciones
        int max = 0;
        for (int i = 0; i < pubs.size(); i++) {
            max++;
            for (int j = 0; j < pubs.get(i).getComentarios().size(); j++) {
                max++;
            }
        }

        muro.setLayout(new GridLayout(max+1,1));

        for (int i = pubs.size()-1; i>-1; i--) {
            muro.add(new PublicacionVista(pubs.get(i)));
            for (int j = pubs.get(i).getComentarios().size()-1 ; j > -1 ; j--) {
                muro.add(new ComentarioVista(pubs.get(i).getComentarios().get(j)));
            } 
        }
        
    
    }
    
    private void refresh(){
        new VentanaVisitante(usser,visit).setVisible(true);
        dispose();
        
    }

}
